[project]
name = "beetles-in-flight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "yt-dlp>=2025.1.26",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
